version: "3.0"
services:
    db:
        container_name: "db"
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=fastapi_db
            - POSTGRES_PASSWORD=fastapi_db
            - POSTGRES_DB=fastapi_db
        ports:
            - "5434:5432"
        networks:
            - custom
    db_test:
        container_name: "db_test"
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=fastapi_test_db
            - POSTGRES_PASSWORD=fastapi_test_db
            - POSTGRES_DB=fastapi_test_db
        ports:
            - "5433:5432"
        networks:
            - custom
networks:
    custom:
        driver: bridge
