"""create_hashed_password

Revision ID: 289dbd40d444
Revises: 23c5e26d02e8
Create Date: 2024-02-19 12:28:53.506216

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "289dbd40d444"
down_revision = "23c5e26d02e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
