"""update user table

Revision ID: 7358cf1f815c
Revises: 3a9756b6287e
Create Date: 2024-02-08 19:06:42.381885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7358cf1f815c'
down_revision: Union[str, None] = '3a9756b6287e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
