"""init

Revision ID: 94c77db1bdbd
Revises: 289dbd40d444
Create Date: 2024-02-19 15:05:33.351615

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "94c77db1bdbd"
down_revision = "289dbd40d444"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
