"""test running migrations

Revision ID: 027483ed9c64
Revises: 8b4b00f11811
Create Date: 2024-02-10 16:17:10.660737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027483ed9c64'
down_revision = '8b4b00f11811'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
