"""test running migrations

Revision ID: 05f2078a7439
Revises: ea86f16d197c
Create Date: 2024-02-08 18:33:21.221944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f2078a7439'
down_revision = 'ea86f16d197c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
