"""test running migrations

Revision ID: 0c326e09d234
Revises: 8c2ad132ec48
Create Date: 2024-02-10 13:04:38.028539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c326e09d234'
down_revision = '8c2ad132ec48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
