"""test running migrations

Revision ID: 102349ba17e8
Revises: 6590761da6f4
Create Date: 2024-02-08 18:50:14.299155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102349ba17e8'
down_revision = '6590761da6f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
