"""test running migrations

Revision ID: 12e25d36e493
Revises: 2f54d5b38988
Create Date: 2024-02-10 16:15:37.504114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e25d36e493'
down_revision = '2f54d5b38988'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
