"""test running migrations

Revision ID: 16819c3c2ef2
Revises: d789a9318ce2
Create Date: 2024-02-08 19:31:57.091006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16819c3c2ef2'
down_revision = 'd789a9318ce2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
