"""test running migrations

Revision ID: 2108447fbff5
Revises: 34614c8d9d34
Create Date: 2024-02-10 15:22:18.460488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2108447fbff5'
down_revision = '34614c8d9d34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
