"""test running migrations

Revision ID: 26611b3e54b9
Revises: ea6acc19713f
Create Date: 2024-02-10 16:19:52.887427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26611b3e54b9'
down_revision = 'ea6acc19713f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
