"""test running migrations

Revision ID: 271f3838f64c
Revises: 42bbb9de9383
Create Date: 2024-02-08 18:45:34.704501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271f3838f64c'
down_revision = '42bbb9de9383'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
