"""test running migrations

Revision ID: 29dcce96b6ee
Revises: 027483ed9c64
Create Date: 2024-02-10 16:18:57.381943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dcce96b6ee'
down_revision = '027483ed9c64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
