"""test running migrations

Revision ID: 2f54d5b38988
Revises: 71bbe7cf0138
Create Date: 2024-02-10 16:10:59.814830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f54d5b38988'
down_revision = '71bbe7cf0138'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
