"""test running migrations

Revision ID: 332381770a62
Revises: 7b126398f3f0
Create Date: 2024-02-10 16:22:15.107025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332381770a62'
down_revision = '7b126398f3f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
