"""test running migrations

Revision ID: 34614c8d9d34
Revises: b3e7b531eec2
Create Date: 2024-02-10 15:21:34.061458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34614c8d9d34'
down_revision = 'b3e7b531eec2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
