"""test running migrations

Revision ID: 42bbb9de9383
Revises: 49d94a55d347
Create Date: 2024-02-08 18:44:48.808493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bbb9de9383'
down_revision = '49d94a55d347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
