"""test running migrations

Revision ID: 43cb17afabe8
Revises: 64de2ab90ffe
Create Date: 2024-02-10 12:56:06.531676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cb17afabe8'
down_revision = '64de2ab90ffe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
