"""test running migrations

Revision ID: 4653c84a5cbe
Revises: a4696f006df8
Create Date: 2024-02-08 18:28:55.196165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4653c84a5cbe'
down_revision = 'a4696f006df8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
