"""test running migrations

Revision ID: 49d94a55d347
Revises: fe52532759bd
Create Date: 2024-02-08 18:37:32.760237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d94a55d347'
down_revision = 'fe52532759bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
