"""test running migrations

Revision ID: 4b78b2b6d79a
Revises: c230ce3e7ce4
Create Date: 2024-02-10 12:45:23.747886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b78b2b6d79a'
down_revision = 'c230ce3e7ce4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
