"""test running migrations

Revision ID: 4e8c180f44cb
Revises: 89a42214d3ae
Create Date: 2024-02-10 12:49:42.111477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8c180f44cb'
down_revision = '89a42214d3ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
