"""test running migrations

Revision ID: 5877b8692a80
Revises: 102349ba17e8
Create Date: 2024-02-08 19:23:04.951965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5877b8692a80'
down_revision = '102349ba17e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
