"""test running migrations

Revision ID: 64de2ab90ffe
Revises: cef60b0bb33a
Create Date: 2024-02-10 12:55:20.743297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64de2ab90ffe'
down_revision = 'cef60b0bb33a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
