"""test running migrations

Revision ID: 6590761da6f4
Revises: 79d459c87aed
Create Date: 2024-02-08 18:49:44.911468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6590761da6f4'
down_revision = '79d459c87aed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
