"""test running migrations

Revision ID: 66788f3a4e61
Revises: e6d4f3c146c7
Create Date: 2024-02-08 18:31:41.786965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66788f3a4e61'
down_revision = 'e6d4f3c146c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
