"""test running migrations

Revision ID: 6eddc82860ba
Revises: 948e1c049333
Create Date: 2024-02-10 13:01:19.694825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eddc82860ba'
down_revision = '948e1c049333'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
