"""test running migrations

Revision ID: 6fc8a1caca4a
Revises: 4e28ff9d3a89
Create Date: 2024-02-08 18:26:57.292954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc8a1caca4a'
down_revision = '4e28ff9d3a89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
