"""test running migrations

Revision ID: 71bbe7cf0138
Revises: 90f6c2e1e438
Create Date: 2024-02-10 15:27:49.501269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bbe7cf0138'
down_revision = '90f6c2e1e438'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
