"""test running migrations

Revision ID: 79d459c87aed
Revises: 7ef143c50c1c
Create Date: 2024-02-08 18:47:46.538136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d459c87aed'
down_revision = '7ef143c50c1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
