"""test running migrations

Revision ID: 7b126398f3f0
Revises: 26611b3e54b9
Create Date: 2024-02-10 16:21:51.961213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b126398f3f0'
down_revision = '26611b3e54b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
