"""test running migrations

Revision ID: 7ef143c50c1c
Revises: dec14a4ed164
Create Date: 2024-02-08 18:46:38.531266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef143c50c1c'
down_revision = 'dec14a4ed164'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
