"""test running migrations

Revision ID: 89a42214d3ae
Revises: 4b78b2b6d79a
Create Date: 2024-02-10 12:47:49.681215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a42214d3ae'
down_revision = '4b78b2b6d79a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
