"""test running migrations

Revision ID: 8b4b00f11811
Revises: 12e25d36e493
Create Date: 2024-02-10 16:16:25.086333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4b00f11811'
down_revision = '12e25d36e493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
