"""test running migrations

Revision ID: 8c2ad132ec48
Revises: 90fbf928b750
Create Date: 2024-02-10 13:04:22.673633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2ad132ec48'
down_revision = '90fbf928b750'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
