"""test running migrations

Revision ID: 90f6c2e1e438
Revises: ee300c3c38b9
Create Date: 2024-02-10 15:26:34.074243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f6c2e1e438'
down_revision = 'ee300c3c38b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
