"""test running migrations

Revision ID: 90fbf928b750
Revises: dfad6374ded0
Create Date: 2024-02-10 13:02:39.872550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fbf928b750'
down_revision = 'dfad6374ded0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
