"""test running migrations

Revision ID: 948e1c049333
Revises: f8d3036ce135
Create Date: 2024-02-10 13:00:53.817752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948e1c049333'
down_revision = 'f8d3036ce135'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
