"""test running migrations

Revision ID: 9b67faaaa529
Revises: e3a51dcc67ba
Create Date: 2024-02-08 19:42:56.935145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b67faaaa529'
down_revision = 'e3a51dcc67ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
