"""test running migrations

Revision ID: 9d3498cb2346
Revises: 29dcce96b6ee
Create Date: 2024-02-10 16:19:08.102745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3498cb2346'
down_revision = '29dcce96b6ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
