"""test running migrations

Revision ID: a0a3ff799c08
Revises: 43cb17afabe8
Create Date: 2024-02-10 12:56:32.545093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a3ff799c08'
down_revision = '43cb17afabe8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
