"""test running migrations

Revision ID: a26ba679fd89
Revises: ed53c10e40fd
Create Date: 2024-02-10 12:59:10.215384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26ba679fd89'
down_revision = 'ed53c10e40fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
