"""test running migrations

Revision ID: a4696f006df8
Revises: 6fc8a1caca4a
Create Date: 2024-02-08 18:28:07.307059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4696f006df8'
down_revision = '6fc8a1caca4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
