"""test running migrations

Revision ID: b3e7b531eec2
Revises: 0c326e09d234
Create Date: 2024-02-10 13:04:48.413210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e7b531eec2'
down_revision = '0c326e09d234'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
