"""test running migrations

Revision ID: b4e41bb8ccb4
Revises: be01e152cf7d
Create Date: 2024-02-08 19:36:33.237738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e41bb8ccb4'
down_revision = 'be01e152cf7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
