"""test running migrations

Revision ID: be01e152cf7d
Revises: 16819c3c2ef2
Create Date: 2024-02-08 19:33:27.572472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be01e152cf7d'
down_revision = '16819c3c2ef2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
