"""test running migrations

Revision ID: c230ce3e7ce4
Revises: d32c9dc6d2e6
Create Date: 2024-02-10 12:42:50.907177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c230ce3e7ce4'
down_revision = 'd32c9dc6d2e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
