"""test running migrations

Revision ID: cef60b0bb33a
Revises: 4e8c180f44cb
Create Date: 2024-02-10 12:51:00.784258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef60b0bb33a'
down_revision = '4e8c180f44cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
