"""test running migrations

Revision ID: d32c9dc6d2e6
Revises: fc9fd5395464
Create Date: 2024-02-10 12:41:33.293445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32c9dc6d2e6'
down_revision = 'fc9fd5395464'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
