"""test running migrations

Revision ID: d74afa0f73f0
Revises: 332381770a62
Create Date: 2024-02-10 16:22:33.240411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74afa0f73f0'
down_revision = '332381770a62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
