"""test running migrations

Revision ID: d789a9318ce2
Revises: 5877b8692a80
Create Date: 2024-02-08 19:28:58.128983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd789a9318ce2'
down_revision = '5877b8692a80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
