"""test running migrations

Revision ID: dec14a4ed164
Revises: 271f3838f64c
Create Date: 2024-02-08 18:46:28.111654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec14a4ed164'
down_revision = '271f3838f64c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
