"""test running migrations

Revision ID: e3a51dcc67ba
Revises: b4e41bb8ccb4
Create Date: 2024-02-08 19:37:00.864125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a51dcc67ba'
down_revision = 'b4e41bb8ccb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
