"""test running migrations

Revision ID: e6d4f3c146c7
Revises: 4653c84a5cbe
Create Date: 2024-02-08 18:29:35.940075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d4f3c146c7'
down_revision = '4653c84a5cbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
