"""test running migrations

Revision ID: ea6acc19713f
Revises: 9d3498cb2346
Create Date: 2024-02-10 16:19:26.739828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6acc19713f'
down_revision = '9d3498cb2346'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
