"""test running migrations

Revision ID: ea86f16d197c
Revises: 66788f3a4e61
Create Date: 2024-02-08 18:31:56.379401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea86f16d197c'
down_revision = '66788f3a4e61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
