"""test running migrations

Revision ID: ed53c10e40fd
Revises: a0a3ff799c08
Create Date: 2024-02-10 12:57:57.254920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed53c10e40fd'
down_revision = 'a0a3ff799c08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
