"""test running migrations

Revision ID: ee300c3c38b9
Revises: 2108447fbff5
Create Date: 2024-02-10 15:26:16.676590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee300c3c38b9'
down_revision = '2108447fbff5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
