"""test running migrations

Revision ID: f8d3036ce135
Revises: a26ba679fd89
Create Date: 2024-02-10 13:00:33.539666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d3036ce135'
down_revision = 'a26ba679fd89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
