"""test running migrations

Revision ID: fb8143d14cb0
Revises: fc8776d48d47
Create Date: 2024-02-08 19:49:10.768643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8143d14cb0'
down_revision = 'fc8776d48d47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
