"""test running migrations

Revision ID: fc8776d48d47
Revises: 9b67faaaa529
Create Date: 2024-02-08 19:44:29.759274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8776d48d47'
down_revision = '9b67faaaa529'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
