"""test running migrations

Revision ID: fc9fd5395464
Revises: fb8143d14cb0
Create Date: 2024-02-10 12:40:12.809146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9fd5395464'
down_revision = 'fb8143d14cb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
