"""test running migrations

Revision ID: fe52532759bd
Revises: 05f2078a7439
Create Date: 2024-02-08 18:35:38.091269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe52532759bd'
down_revision = '05f2078a7439'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
